### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by xcambar** [Pixelik/track-autofill#1]
Hi,
Would that be possible to place the URL-based debugging with something else, like an optional argument (`$(mySelector).trackAutofill({ logging: true});`)?

Some frameworks/libs might not play very well with the extra query param.

**Comment by Pixelik** [comment]
I thought about this but it would require devs to go back to their templates and edit the `trackAutofill({...` line(s) whenever they would like to debug it. Whereas the URL based one can turn debugging on/off at any time, client-side. Maybe it's best that I remove it altogether, most plugins don't have such a feature anyway, I mainly created this for myself when writing the code..

**Comment by Pixelik** [comment]
The devs can now turn debugging on/off by editing the script and setting `var DEBUGGING` to true/false [themselves](https://github.com/Pixelik/track-autofill#debugging).
